### ISSUE TITLE
Make fonts Installable, not only embeddable

### ISSUE THREAD

**Issue by hennejg** [levigo/documentplatform-standard14-fonts#2]
When the fonts are used as downloadable fonts in CSS the fonts work on all browsers except for InternetExplorer. This is due to IE requiring the OS/2 table embedding flags to be set to _installable_. See http://kltf.de/kltf_notes_ie9ttfembeddingbits.shtml for details.

**Comment by krzikams** [comment]
Done with release 1.2.
